### ISSUE TITLE
Configuring locale-prefixes kinda breaks the usage of the attribute `#[AsContentTypeController]`

### ISSUE THREAD

**Issue by KristianH** [storyblok/symfony-bundle#31]
### Description

The Storyblok Symfony Bundle can not correctly handle locale-prefixed routes when using attribute `#[AsContentTypeController]`.

Example (and I really like the usage of the attribute):

```php

#[AsContentTypeController(contentType: Page::class, slug: '/legal')]
final readonly class LegalController
{
    public function __construct(
        private Responder $responder,
        private StoriesApiInterface $stories,
    ) {
    }

    public function __invoke(Request $request, Page $page): Response
    {
        return $this->responder->render('content_types/page/legal.html.twig', [
            'page' => $page,
        ]);
    }
}

```

When URLs like `/de/legal` are used, Symfony’s router matches the route, but the locale (`de`) is **not** correctly reflected in the request. Instead:

- `Request::getLocale()` still returns the default (e.g. `en`)
- The slug passed to the controller includes the locale segment (e.g. `de/legal` instead of `legal`)
- The requested API URL contains the prefix as slug in the URL: 
  - Current: `https://api.storyblok.com/v2/cdn/stories/de/blog?language=en&version=draft`
  - Expected: `https://api.storyblok.com/v2/cdn/stories/blog?language=de&version=draft` 

To solve this behaviour I use this configuration `config/routes/storyblok.yaml`:

```yaml
storyblok:
    resource: '@StoryblokBundle/config/routes.php'
    prefix:
        de: '/de'
        ja: '/ja'
        en: ''
```

But the output of `symfony console debug:router | grep 'storyblok'` also register localized routes for the `storyblok_webhook` route, which is not expected.

**Config without prefix:**

```
storyblok_webhook           POST     ANY      ANY    /webhook/storyblok
storyblok_content_type      ANY      ANY      ANY    /{!slug}
```

**Config with prefix:**

``` 
storyblok_webhook.de        POST     ANY      ANY    /de/webhook/storyblok
storyblok_webhook.ja        POST     ANY      ANY    /ja/webhook/storyblok
storyblok_webhook.en        POST     ANY      ANY    /webhook/storyblok
storyblok_content_type.de   ANY      ANY      ANY    /de/{!slug}
storyblok_content_type.ja   ANY      ANY      ANY    /ja/{!slug}
storyblok_content_type.en   ANY      ANY      ANY    /{!slug}
```

**Expected: Config with prefix:**

```
storyblok_webhook           POST     ANY      ANY    /webhook/storyblok
storyblok_content_type.de   ANY      ANY      ANY    /de/{!slug}
storyblok_content_type.ja   ANY      ANY      ANY    /ja/{!slug}
storyblok_content_type.en   ANY      ANY      ANY    /{!slug}
```

---

## StoryBlok Configuration
Settings > Internationalization > Added Languages:  English (Default), German (de), Japanese (ja)
Content > Folder: `Legal` > Slug: `legal`; Technical name: `page` (saved/published in all languages)

**Comment by silasjoisten** [comment]
@smnandre any idea?

**Comment by smnandre** [comment]
We need to create two route files I guess

**Comment by silasjoisten** [comment]
Thank you @KristianH for the detailed issue. However i am thinking this is not a bug its a feature. I provided a PR which makes it possible to import the routes seperatly. #32 

I will update the symfony flex reciepe accordingly

```yaml
storyblok_content_type:
    resource: '@StoryblokBundle/config/routes/content_type.php'
    prefix:
        # Order is vital (first match wins)
        de: '/de'
        ja: '/ja'
        en: ''

storyblok_webhook:
    resource: '@StoryblokBundle/config/routes/webhook.php'

```
